spring:
  application:
    name: user-mgmt-service

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
    clean-disabled: true
  
  datasource:
    url: jdbc:postgresql://rms.postgres.database.azure.com:5432/usr_mgmt_db
    username: rmsadmin
    password: vfr4VFR$
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#        default_schema: usr_mgmt_db
  
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${PORT:8081}

app:
  jwt:
    secret: qXjYpZmVcDbWnFkLgHsIrOtUeQxSzAaBcDeFgHiJkLmNoPqRsTuVwXyZ0123456789+/ABCDEF
    expiration: 86400000 # 24 hours

logging:
  level:
    com.resourcemanagement: INFO
    org.springframework.security: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true